### ISSUE TITLE
Callback for HttpRequest Execute is called mutliple times, even if authentication is required

### ISSUE THREAD

**Issue by FelixResch** [Web25/http#13]
As seen in the tests ([travis log](https://travis-ci.org/Web25/http/builds/202335576) lines 1395 - 1402) when executing the tests for the synchronous client no exception is thrown, while executing the async test throws an exception:

```
java.lang.AssertionError: Status expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.web25.http.AsyncExecutorHttpTest$testBasicAuthentication$3.invoke(AsyncExecutorHttpTest.kt:139)
	at org.web25.http.AsyncExecutorHttpTest$testBasicAuthentication$3.invoke(AsyncExecutorHttpTest.kt:15)
	at org.web25.http.drivers.client.DefaultHttpRequest.execute(DefaultHttpRequest.kt:119)
	at org.web25.http.AsyncExecutorHttpTest.testBasicAuthentication(AsyncExecutorHttpTest.kt:137)
```

This might be caused, by the request calling the callback even if the request is not finished yet.

**Comment by FelixResch** [comment]
Has been fixed with the mentioning commit
